# Generated by Django 5.0 on 2023-12-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('class_st', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=40)),
            ],
        ),
    ]
